# name: docs

# on:
#   push:
#     branches: [main]
#   pull_request:
#   workflow_dispatch:

# permissions:
#   contents: write

# jobs:
#   docs:
#     runs-on: ubuntu-latest

#     strategy:
#       fail-fast: false
#       matrix:
#         python-version: ['3.10']
#         os: [ubuntu-latest]

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v3
#         with:
#           python-version: ${{ matrix.python-version }}

      # - name: Install dependencies
      #   run: |
      #     pip install uv
      #     uv pip install --system .[docs]

      # - name: Sphinx build
      #   # fail on warnings with `-W`
      #   # run: |
      #   # sphinx-build docs _build -W --keep-going
      #   run: |
      #     sphinx-build docs _build --keep-going

      # - name: Install tree
      #   run: sudo apt-get install tree

      # - name: Print tree
      #   run: |
      #     cd _build
      #     tree -a

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_branch: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: _build/
      #     force_orphan: true



name: docs

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      # Check out source
      - uses: actions/checkout@v2

      # Set up Python
      - name: "Set up Python 3.12"
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Build documentation
      - name: Building documentation
      # uv pip install --system -e ".[dev]"
        run: |
          pip install uv
          uv pip install --system -r docs/requirements.txt
          sphinx-build docs/source docs/build -b dirhtml

      # Deploy
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build

      # # Build documentation
      # - name: Building documentation
      # # uv pip install --system -e ".[dev]"
      # # uv pip install --system -r docs/requirements.txt
      #   run: |
      #     pip install uv
      #     uv pip install --system -e ".[docs]"
      #     sphinx-build docs/source docs/build -b dirhtml

      # # Deploy
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs/build
